set nu
set nocp
set bs=indent,eol,start
set ai
set history=50
set ru
set tabstop=4
set shiftwidth=4
set cul
set et
set sc
set sm
set noeb

if &t_Co > 2 || has("gui_running")
    syntax on
    set hlsearch
endif

filetype plugin on

set enc=utf-8
set fenc=utf-8
set fencs=utf-8,ucs-bom,latin1,gbk,gb2312,iso-8859-1,cp936
set tenc=utf-8

